#██████╗ ███╗   ███╗███████╗███████╗███████╗███████╗███╗   ██╗████████╗██╗ █████╗ ██╗     ███████╗
#██╔══██╗████╗ ████║██╔════╝██╔════╝██╔════╝██╔════╝████╗  ██║╚══██╔══╝██║██╔══██╗██║     ██╔════╝
#██████╔╝██╔████╔██║█████╗  ███████╗███████╗█████╗  ██╔██╗ ██║   ██║   ██║███████║██║     ███████╗
#██╔═══╝ ██║╚██╔╝██║██╔══╝  ╚════██║╚════██║██╔══╝  ██║╚██╗██║   ██║   ██║██╔══██║██║     ╚════██║
#██║     ██║ ╚═╝ ██║███████╗███████║███████║███████╗██║ ╚████║   ██║   ██║██║  ██║███████╗███████║
#╚═╝     ╚═╝     ╚═╝╚══════╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═══╝   ╚═╝   ╚═╝╚═╝  ╚═╝╚══════╝╚══════╝

# built-in cooldowns: (in seconds)
heal.cooldown: 300
feed.cooldown: 120